### ISSUE TITLE
[Docs] Add  steps to installation in local readme

### ISSUE THREAD

**Issue by Ghat0tkach** [swarnavopramanik/Admin-Panel#1]
i would like to work on this issue under GSSOC-23

**Comment by swarnavopramanik** [comment]
Okkk you will work 
And if will deploy in my this app it will be help  for me can you work this proceed

**Comment by Ghat0tkach** [comment]
> Okkk you will work And if will deploy in my this app it will be help for me can you work this proceed
well if you wish to deploy app , we can use netlify . which will directly deploy this using your github repo.
as its project is solely , you should deploy it😅

**Comment by Ghat0tkach** [comment]
@swarnavopramanik 
![image](https://github.com/swarnavopramanik/Admin-Panel/assets/59855919/d42d0921-9fd7-48e0-9cff-0e285a6d9d0b)
you can add gssoc-23 label using this new label

**Comment by swarnavopramanik** [comment]
Can you deploy my app if yes please send me deploy link here

**Comment by Ghat0tkach** [comment]
> Can you deploy my app if yes please send me deploy link here

wait ill try

**Comment by Ghat0tkach** [comment]
@swarnavopramanik so i was trying and found that circular dependies have been used , which are the reason for not getting deployed 
![image](https://github.com/swarnavopramanik/Admin-Panel/assets/59855919/daa6f8fb-69db-4e31-88af-1a47a1ee43e3)

**Comment by swarnavopramanik** [comment]
Oo 🤔
Can you delete or something add in this portion then try it

**Comment by swarnavopramanik** [comment]
Also I have to look this problem

**Comment by Ghat0tkach** [comment]
> Oo 🤔 Can you delete or something add in this portion then try it

hmm ill try , a beginner in react but will give my full shot!!

**Comment by swarnavopramanik** [comment]
Great brother .
