### ISSUE TITLE
GirlScript Summer of Code  level 

### ISSUE THREAD

**Issue by swarnavopramanik** [swarnavopramanik/Admin-Panel#10]

**Comment by swarnavopramanik** [comment]
done

**Comment by Sumit-pd** [comment]
where is the communication channel?

**Comment by swarnavopramanik** [comment]
Which project
One are group here but it not official few Contributor or admin here in this WhatsApp group.

**Comment by Sumit-pd** [comment]
for this project admin panel

**Comment by swarnavopramanik** [comment]
> for this project admin panel

No group are here 
Discord me tag kar skhate ho koe group nahi hee opesource me kase muen pata chale ga or kase group hoga kisi ka nahi hee sayad
