### ISSUE TITLE
[FEATURE] Add CodeQL Workflow

### ISSUE THREAD

**Issue by smty2018** [swarnavopramanik/Admin-Panel#106]
### Description

I want to add the codeql workflow to automate security checks. CodeQL is the code analysis engine developed by GitHub to identify vulnerabilities in code. It will analyze your code and display the results as code scanning alerts. It will be enabled on every push, commit and pull request using GitHub actions

**Comment by swarnavopramanik** [comment]
Not required

Workflow alredy here
