### ISSUE TITLE
[Fix]: Kanban drag and drop

### ISSUE THREAD

**Issue by subrat611** [swarnavopramanik/Admin-Panel#11]
Could you please assign this issue to me?

**Comment by swarnavopramanik** [comment]
Okk you will work for this

**Comment by subrat611** [comment]
Hello @swarnavopramanik this issue is already resolved. 
By  changing the screen size of the browser the Kanban board looks like this
![image](https://github.com/swarnavopramanik/Admin-Panel/assets/77252075/da414e6a-f99c-45a0-8a1b-726f7de266d8)

but when I refresh the page the board can able to scroll.
![image](https://github.com/swarnavopramanik/Admin-Panel/assets/77252075/c3bd4510-42b2-46c6-a781-8d8b70aafd90)

**Comment by swarnavopramanik** [comment]
Good work please merge your code into my code

**Comment by subrat611** [comment]
No changes made by me everything is working fine.

You may close this issue.

**Comment by swarnavopramanik** [comment]
Okkk okk
