### ISSUE TITLE
[FEATURE]: META ELEMENTS TO IMPROVE SEO 🚀

### ISSUE THREAD

**Issue by 0xabdulkhalid** [swarnavopramanik/Admin-Panel#111]
### Description

- The `<meta>` elements in HTML are used to provide metadata or additional information about an HTML document. 
- They help with specifying the character encoding, defining the viewport for responsive design, setting the page title, and providing page descriptions. 
- They assist search engines, browsers, and other web applications in understanding and processing the webpage's content effectively.
- I want to add important Meta elements because in HTML they play a crucial role in providing information about the webpage to browsers and search engines and for the above mentioned reasons.

### Additional information

- I'm a `GSSoC23` Contributor.

**Comment by 0xabdulkhalid** [comment]
Hey there @swarnavopramanik 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you.

**Comment by swarnavopramanik** [comment]
> ### Description
> * The `<meta>` elements in HTML are used to provide metadata or additional information about an HTML document.
> * They help with specifying the character encoding, defining the viewport for responsive design, setting the page title, and providing page descriptions.
> * They assist search engines, browsers, and other web applications in understanding and processing the webpage's content effectively.
> * I want to add important Meta elements because in HTML they play a crucial role in providing information about the webpage to browsers and search engines and for the above mentioned reasons.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> * I'm a `GSSoC23` Contributor.

@0xabdulkhalid  Not requried this changes

**Comment by swarnavopramanik** [comment]
@0xabdulkhalid  not required this change
