### ISSUE TITLE
[DOCS] README.md enhancement

### ISSUE THREAD

**Issue by DivyanshiNarang** [swarnavopramanik/Admin-Panel#121]
### Description

Official documentation links are not added to these buttons. We can add official documentation links of the respective technologies used so that it will be helpful for new contributors.

### Screenshots

<img width="297" alt="image" src="https://github.com/swarnavopramanik/Admin-Panel/assets/74779601/fc49b98a-80ff-4b66-9840-b668750f1fa5">

**Comment by swarnavopramanik** [comment]
@DivyanshiNarang not required any additional documents in my repo
