### ISSUE TITLE
[FEATURE] : Convert PNG, JPG Images File Format into WEBP Format🌟🌟

### ISSUE THREAD

**Issue by NarendraKoya999** [swarnavopramanik/Admin-Panel#122]
### Purpose of This Issue:
- **WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster. WebP lossless images are 26% smaller in size compared to PNGs.**

### Screenshots

![admin-panel-1](https://github.com/swarnavopramanik/Admin-Panel/assets/84512164/d5fc545e-174d-4a47-af78-000e8898e05f)

### Additional information

- **Observe in Screenshot, It's almost Saved 70% of Actual File Size while Converted from JPG into WEBP File Format.**
- **So, I want to work on those Changes in Entire Project Directory.**

**Comment by swarnavopramanik** [comment]
@NarendraKoya999 not required
