### ISSUE TITLE
Develop My Inbox page in User Profile

### ISSUE THREAD

**Issue by MuskanGarg24** [swarnavopramanik/Admin-Panel#13]
@swarnavopramanik @Ghat0tkach  Please assign me this!

**Comment by Ghat0tkach** [comment]
unfortunately im not the maintainer , its @swarnavopramanik  . You shall ask from him

**Comment by swarnavopramanik** [comment]
> unfortunately im not the maintainer , its @swarnavopramanik  . You shall ask from him

Yeah I look this

**Comment by swarnavopramanik** [comment]
> @swarnavopramanik @Ghat0tkach  Please assign me this!

If you can something add in inbox secretion please do it but sure if it work inyou local machis and when you change code and work perfectly then take ss and send to me them merge pull request 👍

**Comment by LaxmanSingh07** [comment]
Hello @swarnavopramanik should I too work on it?  I will eagerly await your response.

**Comment by swarnavopramanik** [comment]
> Hello @swarnavopramanik should I too work on it?  I will eagerly await your response.

Yeahhh sure you will work

**Comment by Ghat0tkach** [comment]
> > Hello @swarnavopramanik should I too work on it?  I will eagerly await your response.
> 
> Yeahhh sure you will work 

I think already @MuskanGarg24 is working on it , if she didn't complete in a week or so , then it could be assigned to @LaxmanSingh07

**Comment by swarnavopramanik** [comment]
Okkk

**Comment by Ghat0tkach** [comment]
its already completed i think @swarnavopramanik we must close it now

**Comment by swarnavopramanik** [comment]
> its already completed i think @swarnavopramanik we must close it now
> 

Yeahhh
