### ISSUE TITLE
[Feat]: Show kanban data by different state

### ISSUE THREAD

**Issue by subrat611** [swarnavopramanik/Admin-Panel#14]
Users can filter out the tasks by:
1. Type
2. Priority
3. Assignee
4. Tags

Could you please assign this issue to me?

**Comment by swarnavopramanik** [comment]
Yeah Please work and change into is

**Comment by subrat611** [comment]
you may close this issue @swarnavopramanik

**Comment by swarnavopramanik** [comment]
> you may close this issue @swarnavopramanik 

Yeahh sure I wil do
