### ISSUE TITLE
My project all are dummy data present Wok to convert real data 

### ISSUE THREAD

**Issue by swarnavopramanik** [swarnavopramanik/Admin-Panel#15]
Who are familiar to mongo db data base please dm me for this work it is difficult but please so 
convert dummy data thoug mongo compass in mongo db to look like use real data .

**Comment by codemaniac-sahil** [comment]
Hello @swarnavopramanik, would you assign this issue to me.

**Comment by swarnavopramanik** [comment]
> Hello @swarnavopramanik, would you assign this issue to me.

Plese Go head 🙂

**Comment by swarnavopramanik** [comment]
> Hello @swarnavopramanik, would you assign this issue to me.

Sure You will work please and after completing please detail screen short share please go ahead

**Comment by codemaniac-sahil** [comment]
Would you please elaborate the issue.

**Comment by swarnavopramanik** [comment]
> Would you please elaborate the issue @swarnavopramanik.

Yeahh sure 
https://github.com/swarnavopramanik/Admin-Panel/blob/main/src/data/dummy.js
This all are dummy data if you convert it's real data with connection to mongo db it could be very beneficial and connect backend part so it could attractive

**Comment by codemaniac-sahil** [comment]
@swarnavopramanik, you want me to make an administration system for applying basic crud operations.

**Comment by swarnavopramanik** [comment]
> @swarnavopramanik, you want me to make an administration system for applying basic crud operations.

Yeahhh

**Comment by swarnavopramanik** [comment]
But make sure dummy dummy data are huge to try to make convert using mongo compass

**Comment by codemaniac-sahil** [comment]
Okay, @swarnavopramanik assign it to me then I will start working on the issue.

**Comment by swarnavopramanik** [comment]
Or you can do anything else make sure it will work properly when you connect backend and make sure steps process are add for other people can see also

**Comment by swarnavopramanik** [comment]
Or you can do anything else make sure it will work properly when you connect backend and make sure steps process are add for other people can see also

**Comment by codemaniac-sahil** [comment]
Okay, @swarnavopramanik I'll do it

**Comment by swarnavopramanik** [comment]
Okkk great

**Comment by LaxmanSingh07** [comment]
@swarnavopramanik should I too work on it?

**Comment by swarnavopramanik** [comment]
This part work another contribute should wait if it not work properly then I will tell you 
Before you work to change something or agg in this admin panel or add something new things so you can go and discuss what are add in porject 🙂

**Comment by swarnavopramanik** [comment]
@LaxmanSingh07  @codemaniac-sahil  any update  ??

**Comment by codemaniac-sahil** [comment]
@swarnavopramanik I am working on it.

**Comment by swarnavopramanik** [comment]
> @swarnavopramanik I am working on it.

great @codemaniac-sahil

**Comment by Kushagra102** [comment]
@swarnavopramanik I am interested in working on this issue. I have extensive knowledge in incorporating such features. Can we use MongoDB Atlas ?

**Comment by swarnavopramanik** [comment]
> @swarnavopramanik I am interested in working on this issue. I have extensive knowledge in incorporating such features. Can we use MongoDB Atlas ?
> 

Yeah sure
