### ISSUE TITLE
Shadow effect to the card in E-Commerce section. [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [swarnavopramanik/Admin-Panel#18]
In light mode ,each card gets mixed with the background, adding shadow effect will be great deal .
Do assign this issue to me under GSSOC 2023 as per your convenience.

![WhatsApp Image 2023-05-22 at 12 47 48 PM](https://github.com/swarnavopramanik/Admin-Panel/assets/96622693/c02dd62f-f3a8-481d-8b56-7100234e93f9)

Just for example in above earning card.

**Comment by swarnavopramanik** [comment]
Yeahh Great observation

Please go ahead and work for this issue

**Comment by mohd-raza** [comment]
@ManishaSwain8 Any updates with this feature??

**Comment by ManishaSwain8** [comment]
already PR is merged @mohd-raza

**Comment by mohd-raza** [comment]
OK, but maker sure from next time after sending a PR you send a message in the issues for no confusion👍
