### ISSUE TITLE
Responsiveness Issues with certain pages 

### ISSUE THREAD

**Issue by TheXro** [swarnavopramanik/Admin-Panel#20]
Certain part of the order, employees and Customer pages overlaps the sidebar when viewed from a smaller screen

Here's the video :

https://github.com/swarnavopramanik/Admin-Panel/assets/84002250/469060e3-9a57-4d32-b0f2-0b97a833f058

**Comment by swarnavopramanik** [comment]
> yes
> please assign this to me under GSSoC

Yeahh yeahh sure you will start work

**Comment by TheXro** [comment]
#27 done please check

**Comment by swarnavopramanik** [comment]
> #27 done please check

Okkk I will check
