### ISSUE TITLE
Readme Updation

### ISSUE THREAD

**Issue by shraddha761** [swarnavopramanik/Admin-Panel#22]
![Screenshot 2023-05-21 160801](https://github.com/swarnavopramanik/Admin-Panel/assets/106100728/fb4d0712-2455-4401-a2a3-7617ccd7b90d)

Adding this badges in readme makes it more attractive assign this issue to me under GSSOC'23 label

**Comment by swarnavopramanik** [comment]
Add please

**Comment by shraddha761** [comment]
Please assign it to me under GSSOC label

**Comment by swarnavopramanik** [comment]
Yeahh yeah I add don't worry all are things I am noted so please add

**Comment by shraddha761** [comment]
@swarnavopramanik Is their any changes I need to done or anything else
