### ISSUE TITLE
we can add a demo video 

### ISSUE THREAD

**Issue by codewithnadeem14502** [swarnavopramanik/Admin-Panel#23]
i think add a demo video will be a good option on the readme. it will increase other fellow contributor experience and i request you to assign me this issue . i will happy to wok with you

**Comment by swarnavopramanik** [comment]
Yes please go and work and make a Vedio 
And som things project releted valueable talk add for mors attractive look other repo and then right according to GSSoC guidline

**Comment by codewithnadeem14502** [comment]
please add gssoc tag and assign me this. i will happy to work on this

**Comment by swarnavopramanik** [comment]
> please add gssoc tag and assign me this. i will happy to work on this

Yeahh I will add GSSoC tag don't worry you start work please

**Comment by codewithnadeem14502** [comment]
Sure, I am starting please assign me this issue

**Comment by swarnavopramanik** [comment]
> Sure, I am starting please assign me this issue 

Yeahh yeah please start

**Comment by codewithnadeem14502** [comment]
i am starting working sir, by tonight i will update you

**Comment by codewithnadeem14502** [comment]
sure bro, but please assign me this 😅

**Comment by swarnavopramanik** [comment]
> sure bro, but please assign me this 😅

Yeah please start work

**Comment by codewithnadeem14502** [comment]
Ok bro I am working on it

**Comment by swarnavopramanik** [comment]
> Ok bro I am working on it 

Yeahhh 🙂
