### ISSUE TITLE
we can add favicon ?

### ISSUE THREAD

**Issue by codewithnadeem14502** [swarnavopramanik/Admin-Panel#25]
A favicon is a small icon or collection of icons associated with a website, web page, or web application. It’s displayed within the browser tabs and bookmarks bar. The examples below show the favicons for Google, Reddit, and Squarespace within the browser tab.  and i think add this will increase the user experience and i request you assign me this issue. happy to work with you

**Comment by swarnavopramanik** [comment]
Greater Idea

Please work for this idea

**Comment by codewithnadeem14502** [comment]
please add gssoc tag and assign me this. i will happy to work on this

**Comment by codewithnadeem14502** [comment]
Assign me

**Comment by swarnavopramanik** [comment]
> Assign me 

Yeahh sure you can start work for it

**Comment by swarnavopramanik** [comment]
> i am starting working sir, by tonight i will update you 

Yeahh sure don't call sir I am student don't worry you can work slowly no problem it okk to delay or late nothing much bigger issue so keep relaxed and work and learn that's more important keep going ❤️

**Comment by codewithnadeem14502** [comment]
sure bro, but please assign me this 😅

**Comment by codewithnadeem14502** [comment]
thank you so much sir

**Comment by mohd-raza** [comment]
@codewithnadeem14502 Any updates with the favicon??

**Comment by kaashikaagrawal** [comment]
can I be assigned this issue if the previous assignee is inactive?

**Comment by codewithnadeem14502** [comment]
by tonight i will send you a PR

**Comment by akanksha984** [comment]
Please assign me this issue under gssoc'23. I would like to work upon this issue
