### ISSUE TITLE
Persist User Settings Across Sessions 

### ISSUE THREAD

**Issue by Kalpanathmajhi** [swarnavopramanik/Admin-Panel#29]
https://github.com/swarnavopramanik/Admin-Panel/assets/71187581/60f726c3-e325-4ee5-8a25-6646158d6d61

Currently, the application stores theme and color settings in the local storage when the user changes them. However, these settings are not used to initialize the state when the application reloads. As a result, the user's chosen settings are lost when they refresh the page or revisit the application later.
I can fix the issue in the ContexProvider
Thanks

**Comment by Kalpanathmajhi** [comment]
https://github.com/swarnavopramanik/Admin-Panel/assets/71187581/7caf109e-c872-41cf-b6dc-167ad6deafc8

**Comment by Kalpanathmajhi** [comment]
heyy @swarnavopramanik just an heads up have you gone thought the issue ?? 
thanks.

**Comment by swarnavopramanik** [comment]
> heyy @swarnavopramanik just an heads up have you gone thought the issue ?? 
> thanks.

Great observation I can't see this part 
Please fix this 
Thank you 😊

**Comment by Kalpanathmajhi** [comment]
Thanks for the reply @swarnavopramanik do assign the issue to me.
Thanks.

**Comment by Kalpanathmajhi** [comment]
Sure thanks a lot and all the best for your exams as well !!!

**Comment by swarnavopramanik** [comment]
> Sure thanks a lot and all the best for your exams as well !!!

Yeahh Thank you brother 😊

**Comment by Kalpanathmajhi** [comment]
Heyy @swarnavopramanik i have submitted Pull request of the fix do check it after you got done with your exam.
Thanks.

**Comment by swarnavopramanik** [comment]
> Heyy @swarnavopramanik i have submitted Pull request of the fix do check it after you got done with your exam.
> Thanks.

Yeahh sure
