### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [swarnavopramanik/Admin-Panel#3]
I would like to improve the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by swarnavopramanik** [comment]
Okk you will work 
Please try to deploy my app and send a deploy link here

**Comment by harshsingh32** [comment]
Assign this issue to me under GSSoC'23.

**Comment by PARTH-1712** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.
