### ISSUE TITLE
Add ContributingGuidelines.md 

### ISSUE THREAD

**Issue by shanvijha30** [swarnavopramanik/Admin-Panel#30]
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shanvijha30** [comment]
@swarnavopramanik could you please assign this issue to me.
Thank you!

**Comment by shanvijha30** [comment]
@swarnavopramanik please assign this issue to me.
And could you add the GSSOC23 label to this issue.

**Comment by swarnavopramanik** [comment]
> @swarnavopramanik please assign this issue to me.
> And could you add the GSSOC23 label to this issue.

Yeahh I will add GSSoC label don't worry

**Comment by shanvijha30** [comment]
@swarnavopramanik could you please assign this issue to me as I have worked on it.

**Comment by shanvijha30** [comment]
@swarnavopramanik I have edited the README.md file and added the contributing guidelines.
Could you assign me this issue after which I will create the pull request.

**Comment by shanvijha30** [comment]
@swarnavopramanik Added PR [#43](https://github.com/swarnavopramanik/Admin-Panel/pull/43)
Please review it.

**Comment by mohd-raza** [comment]
@shanvijha30 Hey there, can you make Contributing.MD more visually appealing. Because currently it seems like reading some books and paragraphs. It would be very helpful if you can do it.
