### ISSUE TITLE
Improving the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [swarnavopramanik/Admin-Panel#31]
I would like to be assigned for GSSOC'23 for this issue

Suggestions:
+ Restructuring the header for a more visually appealing look
+ formatting text in a better manner
+ adding badges for a cool effect
+ other minor changes

**Comment by swarnavopramanik** [comment]
Yeahhh please work in this pattern

**Comment by the-amazing-atharva** [comment]
> Yeahhh please work in this pattern

Working on it soon!
Do add the GSSOC'23 label

**Comment by swarnavopramanik** [comment]
> 
> 
> 
> 
> 
> > Yeahhh please work in this pattern
> 
> Working on it soon!
> Do add the GSSOC'23 label

Yeahh I will add letter don't worry for that
