### ISSUE TITLE
[GSSOC'23]Want to improve the Home page UI 

### ISSUE THREAD

**Issue by piyush-mahajan** [swarnavopramanik/Admin-Panel#34]
Hey!! this project in particular is very amazing and I want to add some UI changes to its home page so it will be more consistent with design and will look very consistent with design as I am a UIUX designer I would love to work on this project

**Comment by swarnavopramanik** [comment]
Yeahh sure brother please please do this 

You can change also other part you are UI ) UX deginer it is great please go ahead and work it ...
My exam is going on when I am return home then I will add GSSoC label

**Comment by piyush-mahajan** [comment]
can you assign it to me?

**Comment by swarnavopramanik** [comment]
> can you assign it to me?

Yeahh sure please go ahead and start working

**Comment by swarnavopramanik** [comment]
when your work is completed please ubdate me with ss and no wories you can work your own free time

**Comment by Kushagra102** [comment]
Hey @swarnavopramanik  I would like to work on this. And improve the UI for the frontend.

**Comment by swarnavopramanik** [comment]
> Hey @swarnavopramanik  I would like to work on this. And improve the UI for the frontend.
> 

Okk
