### ISSUE TITLE
Template for people to have a proper format for bug fix, pull requests, new feature addition etc. 

### ISSUE THREAD

**Issue by tuhinaww** [swarnavopramanik/Admin-Panel#35]
| Field | Value                           |
|-------|---------------------------------|
| About | Template for people to have a proper format for bug fix, pull requests, new feature addition etc. |
| Title |       Feature request             |
| **Is your feature request related to a problem? Please describe.** | New Contributors are not able to follow a proper format to create issue for bug fixes, pull request,  new feature additions etc. |
| **Describe the solution you'd like**                               | I can provide ".github" folder with all the necessary templates required |
| **Additional context**                                             | I am from GSSOC'23 you can assign this issue to me |

**Comment by tuhinaww** [comment]
Please assign this issue to me. @swarnavopramanik

**Comment by swarnavopramanik** [comment]
> Please assign this issue to me. @swarnavopramanik 

Okkk you can work this issue

**Comment by swarnavopramanik** [comment]
> Please assign this issue to me. @swarnavopramanik 

Okk you can start working for this issue

**Comment by swarnavopramanik** [comment]
I will add GSSoC level letter

**Comment by tuhinaww** [comment]
Suree!! I will start working on this. But you haven't assigned this issue to me yet. 
![image](https://github.com/swarnavopramanik/Admin-Panel/assets/119059108/a9b24a6c-3ca2-4aa6-9328-95328ee17b79)
Please assign it from here :)

**Comment by tuhinaww** [comment]
I have started working on it. I will update once I finish it!

**Comment by swarnavopramanik** [comment]
> I have started working on it. I will update once I finish it! 

Okk sure

**Comment by Ghat0tkach** [comment]
@tuhinaww only add the PR template as #42 already included issue templates .
