### ISSUE TITLE
[Improvement and Addition of Feature] I want to add some resources, Notes section, improve the UI of resources section

### ISSUE THREAD

**Issue by Anshika-Jain02** [swarnavopramanik/Admin-Panel#37]
# I would like to add/improve the below features
- I would like to add a Notes section where we can put highly recommended notes on the topic and I would like to add my notes too being a passionate web developer
- I would like to add some highly recommended resources (videos, websites, challenges, tools, books)
- I want to improve the alignment of cards like creating proper space between them so, it becomes consistent with the viewport width

**Please assign this issue to me under Gssoc'23**
![Web resources hub](https://github.com/swarnavopramanik/Admin-Panel/assets/104912087/e9414f20-c807-4724-bd2f-0fc03bafaa51)

**Comment by swarnavopramanik** [comment]
No please this is not notes app or not college notes sharing app this is different types app so please I will assign to you this work 
Sorry...
