### ISSUE TITLE
Improving the Ecommerce.jsx

### ISSUE THREAD

**Issue by harshsingh32** [swarnavopramanik/Admin-Panel#4]
I would like to work on improving the Ecommerce.jsx of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue to me under GSSoC'23. please assign this issue to me.

**Comment by swarnavopramanik** [comment]
Yes sure you work this is nice identify
And one things if you know little bit on mongodb you can connect also because trance of dummy deta are here in my project if you know convert dummy deta to real deta 

Please work also .

**Comment by LaveshK11** [comment]
I am highly interested in working on an exceptional e-commerce project as a MERN stack developer. With expertise in both front-end and back-end development, I am confident that I can contribute significantly to the success of this project. I would appreciate the opportunity to discuss further details and commence working on this project as soon as possible. Please consider assigning this task to me, and I will be ready to initiate development promptly

**Comment by swarnavopramanik** [comment]
Yeah sure 
Can you try to deploy my app 1st some issue is coming for my side I will not deploy one Contributor are not can you try ones

**Comment by harshsingh32** [comment]
Sir, I have relevant experience and skillset to resolve the issue. I have experience as a full stack developer, and I would like to work on this issue.

**Comment by swarnavopramanik** [comment]
One contribute work connection in mongo db let's wait I will see and if it not do then I will assign you to this 
This time I will describe all things and asign also

**Comment by swarnavopramanik** [comment]
> Sir, I have relevant experience and skillset to resolve the issue. I have experience as a full stack developer, and I would like to work on this issue.

Yeah sure please do it 
And when it will run perfect then do ss and send here then merge pull request

**Comment by LaveshK11** [comment]
Please let me know if you need help 
Thank you

**Comment by PARTH-1712** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.
