### ISSUE TITLE
Adding a feed back section [GSSOC'23]

### ISSUE THREAD

**Issue by kharshita590** [swarnavopramanik/Admin-Panel#40]

**Comment by swarnavopramanik** [comment]
Add please

**Comment by kharshita590** [comment]
Can your provide me your mail so , whenever the user gives feed back , that would go on your e-mail

**Comment by swarnavopramanik** [comment]
> Can your provide me your mail so , whenever the user gives feed back , that would go on your e-mail

Okkk 

Email : swarnavo.pramanik8697@gmail.com

**Comment by kharshita590** [comment]
Hey can you tell me how to pass checks , there are so many errors which are not related to only mine editing
