### ISSUE TITLE
Project is not deploy in any site 

### ISSUE THREAD

**Issue by swarnavopramanik** [swarnavopramanik/Admin-Panel#41]
![Screenshot (517)](https://github.com/swarnavopramanik/Admin-Panel/assets/105142693/b063894a-9ccc-47b1-8d66-6054c294100e)

**Comment by Ghat0tkach** [comment]
did we made any progress yet?

**Comment by swarnavopramanik** [comment]
> did we made any progress yet? 
> 

Yeahhh

**Comment by swarnavopramanik** [comment]
I will try to deploy but it will not

**Comment by swarnavopramanik** [comment]
> I will try to deploy but it will not
> 
> 

And my Netfly account is not open long time 

So please try anyone

**Comment by Ghat0tkach** [comment]
wahi react me error arha is karan
#1 mentioned the screenshots

**Comment by abhijeetnishal** [comment]
Their is problem during build

**Comment by parth782** [comment]
can I try  if there are still problems in hosting the project?

**Comment by mohd-raza** [comment]
Hey guys myself Mohammed Raza, one of the mentors of this project. Just want to have an update whether the issues are solved or not for hosting

**Comment by swarnavopramanik** [comment]
> Hey guys myself Mohammed Raza, one of the mentors of this project. Just want to have an update whether the issues are solved or not for hosting



> the

@mohd-raza  Not solve dada

**Comment by crocmons** [comment]
want to solve it as a gssoc23 contributor ..I want to host it on vercel/netlify can I do it?

**Comment by swarnavopramanik** [comment]
> want to solve it as a gssoc23 contributor ..I want to host it on vercel/netlify can I do it?

Yeahh you will do 
But I think it will no work because alredy try other contributor and me also 
But you can try again @crocmons

**Comment by crocmons** [comment]
@swarnavopramanik actually I figure out the error is coming out for the eslint there are lot of errors such as indentation, spacing, commas ...that's why npm run build failed..please fix the eslint then all are good to go..

**Comment by Ghat0tkach** [comment]
> @swarnavopramanik actually I figure out the error is coming out for the eslint there are lot of errors such as indentation, spacing, commas ...that's why npm run build failed..please fix the eslint then all are good to go..

actually the main error is use of cyclic components , I have fixed the rest ones already

**Comment by crocmons** [comment]
> > @swarnavopramanik actually I figure out the error is coming out for the eslint there are lot of errors such as indentation, spacing, commas ...that's why npm run build failed..please fix the eslint then all are good to go..
> 
> actually the main error is use of cyclic components , I have fixed the rest ones already

nope check out this
![Uploading Screenshot (416).png…]()

**Comment by Ghat0tkach** [comment]
oh my goodness , i didnt fetched the current repo looks like the rest of the contributers didnt paid attention to these errors . It was like 5-6 when i fixed them now they are a lot more.

**Comment by crocmons** [comment]
hm right

**Comment by Ghat0tkach** [comment]
@swarnavopramanik we have to add level0, level1, level2, and level3 labels for gssoc 😅.
I suggest you to add level3 label on this specific issue as it was a fairly big issue to tackle 😅

**Comment by swarnavopramanik** [comment]
🥲🤣🤣😂😂😂

**Comment by swarnavopramanik** [comment]
Level -3 
Any one not solve this problem

**Comment by swarnavopramanik** [comment]
😂😂🤣🤣🤣
