### ISSUE TITLE
Add scroll button from bottom to top

### ISSUE THREAD

**Issue by gaur15** [swarnavopramanik/Admin-Panel#48]
### Description

adding scroll button from top to bottom or bottom to top to make navigation easier

**Comment by swarnavopramanik** [comment]
> ### Description
> 
> adding scroll button from top to bottom or bottom to top to make navigation easier
> 
> ### Screenshots
> 
> _No response_
> 
> ### Additional information
> 
> _No response_

Okkk you will add

**Comment by deveRana** [comment]
@swarnavopramanik please assign this task to me .

**Comment by deveRana** [comment]
ok , i will start working on it

**Comment by deveRana** [comment]
@swarnavopramanik  i am getting error , i installed all dependencies then also i am getting error[](url)
![Uploading Screenshot 2023-05-31 132038.png…]()

**Comment by swarnavopramanik** [comment]
> 
> ![erro](https://github.com/swarnavopramanik/Admin-Panel/assets/87362652/3c058cd3-30e6-40c2-b9dc-30ac07d6b714)
> @swarnavopramanik  i am getting error , i installed all dependencies then also i am getting error[
> 

Try to find why this error coming and fix this
