### ISSUE TITLE
[DOCS] Add Contributors Graph

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [swarnavopramanik/Admin-Panel#53]
* I would like to incorporate a contributor graph in the README.md file as a means of acknowledging and appreciating the work of contributors. I kindly request to be assigned this particular issue.
* Here is an example of the work I aspire to undertake within this project.

![Screenshot (80)](https://github.com/swarnavopramanik/Admin-Panel/assets/112751524/e5d57d47-cc7e-485c-a096-7f58c5420db1)

**Comment by swarnavopramanik** [comment]
No not required
