### ISSUE TITLE
adding tech stack badges and shields to the readme

### ISSUE THREAD

**Issue by mridulsaggi** [swarnavopramanik/Admin-Panel#57]
### Description

i would like to add tech stack badges and shield so the readme

**Comment by swarnavopramanik** [comment]
Okk you will add

**Comment by swarnavopramanik** [comment]
@mridulsaggi  tech badge means witch badge ??? Please don't add contributor badge

**Comment by mridulsaggi** [comment]
Tech stack badges are the badges for the technologies used like javascript html css etc

**Comment by swarnavopramanik** [comment]
@mridulsaggi okk you can add in fast add React Js badge it is totally based on this language above 95% use

**Comment by mridulsaggi** [comment]
Ok bro sure!
Pls assign me the issue and i will create the pull request

**Comment by swarnavopramanik** [comment]
> Ok bro sure! Pls assign me the issue and i will create the pull request

Already assign please start  work
