### ISSUE TITLE
vercel link is not working 

### ISSUE THREAD

**Issue by codewithnadeem14502** [swarnavopramanik/Admin-Panel#6]
I request you please add the working URL for your project

**Comment by swarnavopramanik** [comment]
Sorry Vedio are here if you look working then start repo fork the. Clone then npm instayand then npm start look your local machine
Because I will fail to deploy and one contributor also fail deploy 
So if look this dashboard you run your local machine 🙂

**Comment by codewithnadeem14502** [comment]
Ok

**Comment by Abhishek-00** [comment]
Can you assign this issue to me. I am GSSoC'23 contributer.

**Comment by swarnavopramanik** [comment]
This will not work 
But if try please go ahead

**Comment by Abhishek-00** [comment]
We can deploy It to vercel manually.

**Comment by Abhishek-00** [comment]
Another soloution is that we can deploy it to netlify manually.

**Comment by codewithnadeem14502** [comment]
i have an idea. i want to try this. and i think it will work. so assign me to work upon thank you

**Comment by swarnavopramanik** [comment]
> i have an idea. i want to try this. and i think it will work. so assign me to work upon thank you 

Yeahh please try once
