### ISSUE TITLE
Adding functionality to shopping cart section

### ISSUE THREAD

**Issue by Yash7426** [swarnavopramanik/Admin-Panel#7]
Adding functionality to add and subtract button on shopping cart section
i would like to work on the issue , please assign it to me

**Comment by swarnavopramanik** [comment]
Yeahh please work and when this task complete then Taka a ss and send here to realise what are working right now 
And it will help for me if it you deploy this app because my app is not deployed some issues are coming. 

Go ahead 👍

**Comment by Yash7426** [comment]
Okay , I'll try deploying the app.
