### ISSUE TITLE
[GSSOC'23] Add a custom report 

### ISSUE THREAD

**Issue by vivxsdb** [swarnavopramanik/Admin-Panel#72]
### Description

A new feature that could be added to the Admin Dashboard is the ability to generate custom reports and export them as PDF or CSV files. This would allow administrators to select specific data points and metrics, create reports with charts, tables, and visualizations, and export them in different formats. It would enhance usability and flexibility, making it easier to analyze and share data with team members and stakeholders. Can U please assign me this issue under GSSOC'23

**Comment by swarnavopramanik** [comment]
@vivxsdb yes please add this features

**Comment by vivxsdb** [comment]
Can u please assign me this under GSSOC'23

**Comment by swarnavopramanik** [comment]
> Can u please assign me this under GSSOC'23

Don't worry I will add letter
