### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by ayushi0809** [swarnavopramanik/Admin-Panel#73]
### Description

Hi @swarnavopramanik ,
I suggest adding a login/register functionality for the admin panel.
Where user can register himself/herself, he/she can also log in with their Google account
Please let me know so I can start working on this feature.

**Comment by swarnavopramanik** [comment]
@ayushi0809 yes please add sign in Login option
I think you use firebase Google authentication whatever you can work this feature

**Comment by ayushi0809** [comment]
Can you please assign this issue to me under GSoc23

**Comment by swarnavopramanik** [comment]
> Can you please assign this issue to me under GSSOC23

Yeahh I will do letter don't worry

**Comment by Deepanshu0703** [comment]
@swarnavopramanik   may i work on this issue it's been two weeks so can you assign this is issue to me

**Comment by ayushi0809** [comment]
I am working on it
