### ISSUE TITLE
the feedback form gets submitted even when not a valid email is entered .

### ISSUE THREAD

**Issue by mridulsaggi** [swarnavopramanik/Admin-Panel#74]
### Description

the feedback form gets submitted even when not a valid email is entered . also the sent text is not clearly visible and lacks font design.

### Screenshots

![image](https://github.com/swarnavopramanik/Admin-Panel/assets/91930535/e7a4902e-e160-40cd-bf26-d9a85993ce55)

### Additional information

pls assign me this issue as i would like to work on this and enhance the ui.

**Comment by swarnavopramanik** [comment]
Yeahh sure you work 
In the letter I will assigned and attach GSSoC logo

**Comment by akanksha984** [comment]
Please assign me this issue i would like to work upon it under gssoc'23
