### ISSUE TITLE
A different page for Feedback 

### ISSUE THREAD

**Issue by ritikalath30** [swarnavopramanik/Admin-Panel#77]
### Description

**Instead of having feedback on every page, we can have a tab in the navbar that will direct us to a different page for sending the feedback.**

@swarnavopramanik could you assign me the task of adding another page just for feedback?

**Comment by ritikalath30** [comment]
Thankyou.

**Comment by ritikalath30** [comment]
Hey, @swarnavopramanik may i know what changes are to be incorported so that my code gets merged?

**Comment by swarnavopramanik** [comment]
> Hey, @swarnavopramanik may i know what changes are to be incorported so that my code gets merged?

I think your code is already merged
