### ISSUE TITLE
[Deploy]Site Deployement

### ISSUE THREAD

**Issue by Ghat0tkach** [swarnavopramanik/Admin-Panel#78]
The current site isnt deployed and due to which most of the issues or PR generated impacts isnt visible .It has also led to the distruptive interfaces like 
![image](https://github.com/swarnavopramanik/Admin-Panel/assets/59855919/958cf30c-4298-4c21-af77-7c4f879873c3)

We should only merge PR which have proper screenshots so that we can be assured of it.

Our main priority is to fix the issue and the main issue is
![image](https://github.com/swarnavopramanik/Admin-Panel/assets/59855919/5cfed124-c377-4470-b8fe-7126ec021aec)

Every PR should be checked that its not raising any other issues except this.
@swarnavopramanik what are your thoughts?

**Comment by swarnavopramanik** [comment]
Yeah you are right 🥲
