### ISSUE TITLE
Enhancing User Profile And Giving More Control

### ISSUE THREAD

**Issue by chaitanyarora** [swarnavopramanik/Admin-Panel#8]

**Comment by swarnavopramanik** [comment]
Yeah you work it is for more function to add  👍

**Comment by chaitanyarora** [comment]
Thankyou Sir!

**Comment by swarnavopramanik** [comment]
Please don't call sir I am also pursuing Btech and also I will be part as Contributor .👍

**Comment by chaitanyarora** [comment]
Okay. Can you please assign this issue to me and label it as GSSoC 2023. So that other people are aware of this.

Here's and example how other Project Admins are doing!

![image](https://github.com/swarnavopramanik/Admin-Panel/assets/85432418/e28af597-a638-422f-97b1-e645bbfbb707)

**Comment by swarnavopramanik** [comment]
Please don't call sir I am also pursuing Btech and also I will be part as Contributor .👍

Yeah sure can you do this ?

**Comment by swarnavopramanik** [comment]
This label can add please 😀

**Comment by chaitanyarora** [comment]
> Please don't call sir I am also pursuing Btech and also I will be part as Contributor .👍
> 
> Yeah sure can you do this ?

Yes I'll add some more functionalities to the panel. Can we connect over LinkedIn? Here's mine https://www.linkedin.com/in/chaitany-arora-693872201/

**Comment by chaitanyarora** [comment]
> This label can add please 😀

Is this project registered in GSSoC 2023?

**Comment by swarnavopramanik** [comment]
> > Please don't call sir I am also pursuing Btech and also I will be part as Contributor .👍
> > 
> > Yeah sure can you do this ?
> 
> Yes I'll add some more functionalities to the panel. Can we connect over LinkedIn? Here's mine https://www.linkedin.com/in/chaitany-arora-693872201/

Yeahh check your LinkedIn

**Comment by swarnavopramanik** [comment]
Yeahh project registrar in GSSoC please add level in GSSoC 2023

**Comment by chaitanyarora** [comment]
> Yeahh project registrar in GSSoC please add level in GSSoC 2023

Didn't get you? What level should I add and where?

**Comment by swarnavopramanik** [comment]
> dd

Add please

**Comment by mohd-raza** [comment]
Any updates @chaitanyarora @PARTH-1712 ??

**Comment by PARTH-1712** [comment]
Kindly review my pull request.

**Comment by PARTH-1712** [comment]
Kindly review/merge my pull request @swarnavopramanik

**Comment by swarnavopramanik** [comment]
> Kindly review/merge my pull request @swarnavopramanik

I think nothing new PR are created you so anything are not coming in front of me @PARTH-1712

**Comment by PARTH-1712** [comment]
Okay, thanks. @swarnavopramanik
