### ISSUE TITLE
[FEATURE] Deploy website live

### ISSUE THREAD

**Issue by sumitkr2000** [swarnavopramanik/Admin-Panel#85]
### Description

Hey @swarnavopramanik Please deploy the website live so I can contribute to your website. When the website is deployed please reply to this issue. Thanks!

**Comment by swarnavopramanik** [comment]
> ### Description
> Hey @swarnavopramanik Please deploy the website live so I can contribute to your website. When the website is deployed please reply to this issue. Thanks!
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

@sumitkr2000 Please fork and run your machine because I will fail many time to deploy in my site sorry for that please fork and run it cool for you and if you like it please give a start for my project
