### ISSUE TITLE
[GSSOC'23] Adding Login and SignUp feature 

### ISSUE THREAD

**Issue by vivxsdb** [swarnavopramanik/Admin-Panel#86]
### Description

Actually I want to provide Login and signup feature So that users can Use the website Can U plz assign me this issue under GSSOC'23

**Comment by vivxsdb** [comment]
I want to use mongoDb for it

**Comment by swarnavopramanik** [comment]
> I want to use mongoDb for it
> 

Okkk no problem

**Comment by vivxsdb** [comment]
Can u assign me this issue under GSSOC 23

**Comment by swarnavopramanik** [comment]
@vivxsdb  What are the progress for this issue ??

**Comment by vivxsdb** [comment]
Write now writing the backend code and going to design the front end part

**Comment by vivxsdb** [comment]
Due my exams it is taking time

**Comment by vivxsdb** [comment]
@mohd-raza or @arnab2001  actually I have some doubt regarding my issue can U please help me with that

**Comment by swarnavopramanik** [comment]
> @mohd-raza or @arnab2001  actually I have some doubt regarding my issue can U please help me with that

@mohd-raza @arnab2001  heyy mentor please kindly look into this issue

**Comment by swarnavopramanik** [comment]
> @mohd-raza or @arnab2001  actually I have some doubt regarding my issue can U please help me with that

@mohd-raza @arnab2001  heyy mentor please kindly look into this issue

**Comment by vivxsdb** [comment]
Actually what structure should I provide for the backend

**Comment by vivxsdb** [comment]
Like what should be the schema and the user functionality should I provide

**Comment by komalioruganti** [comment]
I want to work on this issue. Can you assign me this?

**Comment by vivxsdb** [comment]
No It is my idea
