### ISSUE TITLE
[FEATURE] Add the prettier linter workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [swarnavopramanik/Admin-Panel#87]
### Description

Add the prettier linter to ensure proper linting of the code. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions.

I would like to work on this as a part of GSSoC 23.

**Comment by swarnavopramanik** [comment]
I don't understand what are the issue cam tell me again in brief or any screenshot @metabiswadeep

**Comment by metabiswadeep** [comment]
@swarnavopramanik I am talking about adding the linter GitHub action. This will help ensure proper linting everytime a commit is pushed into the repo or a pull request is raised for the repo. This helps ensure better code readability for new users/contributors to the repo.
