### ISSUE TITLE
The feedback div does not change in dark mode

### ISSUE THREAD

**Issue by OmAgarwal8979** [swarnavopramanik/Admin-Panel#89]
### Description

The feedback div does not change in dark mode

### Screenshots

![image](https://github.com/swarnavopramanik/Admin-Panel/assets/89903819/70fa8a90-6231-4a52-a963-802b0cf5d571)

**Comment by arnab2001** [comment]
you can go ahead with the issue

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I would like to work upon this issue

**Comment by swarnavopramanik** [comment]
@akanksha984 not required this time
