### ISSUE TITLE
[FEATURE] Add CodeQL Workflow

### ISSUE THREAD

**Issue by abhinav-m22** [swarnavopramanik/Admin-Panel#93]
### Description

The repository has javascript code but it lacks workflow for code inspection.

The codeql.yml workflow file will be added by me to automate security checks.

CodeQL is a code analysis tool, to find vulnerabilities in programs. 
The code will be examined, and the results will be presented as code scanning alerts. 
Every push, commit, and pull request that uses GitHub actions will have it enabled.

### Additional information

I want to work on this issue under GSSoC'23

**Comment by abhinav-m22** [comment]
Please assign the issue to someone else as discussed.
Thank you!

**Comment by swarnavopramanik** [comment]
> Please assign the issue to someone else as discussed. Or we can close the issue.
> Thank you!

Sure I will assign you
